### ISSUE TITLE
PDL::DateTime

### ISSUE THREAD

**Issue by zmughal** [EntropyOrg/p5-Data-Frame#18]
Pandas:

``` python
df.time_col.weekday
```

R

``` r
?Date
?POSIXt
?weekdays
?seq.Date
```

**Comment by kmx** [comment]
Hi Zaki,

do you have some particular ideas how PDL::DateTime should be implemented?

I am using my module (not released as it is still an ugly hack) that implements PDL::SerialDate (more or less the serial date from matlab). It basically is a PDL (Long or LongLong) with overloaded stringification (to print date) and some special constructors like `new_from_ymd()` and few extra methods. Now it handles only dates but I can imagine (although not tested) that with underlying PDL of type Double it might also handle date+time.

**Comment by zmughal** [comment]
I was thinking about storing the POSIX epoch time in a subclass of `PDL::Long`. It would be like R's [`POSIXct`](http://stat.ethz.ch/R-manual/R-devel/library/base/html/DateTimeClasses.html). And it will support methods that extract out the weekday (returning a `PDL::Factor` subclass) or month (another `PDL::Factor` subclass). There may also be a method that returns a `PDL::SV` full of `DateTime(::Tiny)` instances.

**Comment by kmx** [comment]
I have started some experiments. I am sub-classing `PDL::LongLong` internally keeping number of microseconds (positive or negative) since `1970-01-01`. Microseconds might come handy when dealing with high-frequency data. LongLong enables us to handle date time range `0001-01-01 00:00:00.000000` .. `9999-12-31 23:59:59.999999` with microsecond precision. 

BTW LongLong + nanosecond precision would limit us to date range `1677-09-21T00:12:44` .. `2262-04-11T23:47:15`

Ad converting date time values to "some" instances - `DateTime` is not a good option performance-wise, `Time::Moment` is very promising.

**Comment by kmx** [comment]
Hi Zaki,

FYI my hacking on `PDL::DateTime` is here
* https://github.com/kmx/pdl-datetime/blob/master/lib/PDL/DateTime.pm
* https://github.com/kmx/pdl-datetime/blob/master/lib/PDL/DateTime.pod

Any comments are welcome.

**Comment by zmughal** [comment]
Cool! I'll definitely follow along!

**Comment by kmx** [comment]
I have finish kind of a initial `PDL::DateTime` version (see my repo). It only needs PDL core with longlong-double fix

**Comment by kmx** [comment]
Zaki,

I want to ask if your original plan was to have `PDL::DateTime` a part of `Data-Frame` distribution or a separate module. Is it OK for you if I release `PDL::DateTime` as my module to CPAN?

My plan is to wait for `PDL-2.014` (longlong fixes, you know) and then release `PDL::DateTime` + also a new versions of `PDL::IO::DBI` and `PDL::IO::CSV` which will have a support for automatic conversion of DATETIME data to `PDL::DateTime` piddles.

--kmx

**Comment by zmughal** [comment]
On 2015-10-05 at 03:56:20 -0700, kmx wrote:
> Zaki,
> 
> I want to ask if your original plan was to have `PDL::DateTime` a part of `Data-Frame` distribution or a separate module. Is it OK for you if I release `PDL::DateTime` as my module to CPAN?
> 
> My plan is to wait for `PDL-2.014` (longlong fixes, you know) and then release `PDL::DateTime` + also a new versions of `PDL::IO::DBI` and `PDL::IO::CSV` which will have a support for automatic conversion of DATETIME data to `PDL::DateTime` piddles.

A separate module is perfectly fine. I only made reference to it here
because I was going through the functionality of Pandas from Python
which includes its own time series specific data structure.

Cheers,
-- Zaki Mughal

**Comment by zmughal** [comment]
No longer needed as @kmx has released <https://metacpan.org/pod/PDL::DateTime>.
