### ISSUE TITLE
Switch to Github Actions

### ISSUE THREAD

**Issue by stphnlyd** [EntropyOrg/p5-Data-Frame#31]
Looks like Travis is much more restricted today. And I easily hit its limitations. We probably can see if we can reuse PDL's setup https://github.com/PDLPorters/pdl

**Comment by mohawk2** [comment]
Good idea! A better (easier, and more suitable) starting-point for CI config to cargo-cult from would be PDL-Stats rather than full PDL.

**Comment by zmughal** [comment]
Or <https://github.com/ebaudrez/Test-PDL/tree/master/.github/workflows>, since it supports `dzil`.

I'll put it together.
